// resetPassword.js
module.exports = (user, resetLink) => {
  const textMessage = `
Hello ${user.name},

Your password reset link has been generated by the admin.

You can now reset your password using the link below:
${resetLink}

⚠️ Please note: This link will expire in 20 minutes.
If you did not request this change, please contact support immediately.

Regards,
Admin
`;

  const htmlMessage = `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Password Reset</title>
  </head>
  <body style="margin:0; padding:0; font-family: Arial, sans-serif; background-color:#f5f5f5;">
    <table width="100%" cellspacing="0" cellpadding="0" style="background-color:#f5f5f5; padding:20px;">
      <tr>
        <td align="center">
          <table width="600" cellspacing="0" cellpadding="0" style="background:#ffffff; border-radius:8px; overflow:hidden;">
            
            <!-- Header with Logo -->
            <tr>
              <td style="background:#007bff; padding:20px; text-align:center;">
                <img src="http://localhost:5173/eonestep/src/assets/logo.png" alt="Logo" width="120" style="display:block; margin:0 auto;" />
              </td>
            </tr>

            <!-- Content -->
            <tr>
              <td style="padding:30px; color:#333;">
                <h2 style="margin-top:0; color:#007bff;">Hello ${user.name},</h2>
                <p>Your password reset has been <b>generated by the admin</b>.</p>
                <p>You can now reset your password using the link below:</p>
                
                <!-- Reset Button -->
                <p style="text-align:center; margin:30px 0;">
                  <a href="${resetLink}" 
                     style="background:#007bff; color:#fff; padding:12px 24px; text-decoration:none; border-radius:4px; display:inline-block;">
                    Reset Password
                  </a>
                </p>
                
                <p style="color:#666;">⚠️ Please note: This link will expire in <b>20 minutes</b>.</p>
                <p>If you did not request this change, please contact support immediately.</p>
                
                <p style="margin-top:30px;">Regards,<br/>Admin</p>
              </td>
            </tr>

            <!-- Footer -->
            <tr>
              <td style="background:#f0f0f0; padding:15px; text-align:center; font-size:12px; color:#888;">
                &copy; ${new Date().getFullYear()} Your Company. All rights reserved.
              </td>
            </tr>

          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
`;

  return { text: textMessage, html: htmlMessage };
};
